language: python
sudo: false
python:
- 2.7
- 3.5
- 3.6
- 3.7

install:
- pip install virtualenv tox docutils coveralls

script:
- python setup.py test
- python setup.py check -r

after_success:
- coveralls
